Aangegeven in welke issues vragen aan bod kunnen komen
VNG-Realisatie/gemma-verwerkingen pull request #7
Opened 2018-03-07 23:00 UTC by adgerrits

2018-03-08 09:44 UTC, ehotting requested changes
Mooier om ze te linken aan issues denk ik

2018-03-08 11:24 UTC, michielverhoef commented
Goede bijdrage

2018-03-08 15:11 UTC, joelkoeckhoven submitted a review, later dismissed

2018-03-09 14:02 UTC, adgerrits commented
Is ondertussen achterhaald en kan gesloten worden.

2018-03-09 14:02 UTC, closed without merging